name: flutter_template
description: Boilarplate template of Flutter GetX.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # cupertino_icons: ^1.0.4
  common:
    path: ./modules/common
  # https://pub-web.flutter-io.cn/packages/get
  get: ^5.0.0-release-candidate-9
  # https://pub-web.flutter-io.cn/packages/flutter_svg
  flutter_svg: ^2.0.7
  # https://pub-web.flutter-io.cn/packages/dio
  dio: ^5.6.0
  # https://pub-web.flutter-io.cn/packages/shared_preferences
  shared_preferences: ^2.3.2
  # https://pub.dev/packages/easy_localization
  easy_localization: ^3.0.7
  # https://pub-web.flutter-io.cn/packages/cached_network_image
  cached_network_image: ^3.2.3
  # https://pub-web.flutter-io.cn/packages/animations
  animations: ^2.0.11
  # https://pub-web.flutter-io.cn/packages/logger
  logger: ^2.4.0
  # https://pub-web.flutter-io.cn/packages/pretty_dio_logger
  pretty_dio_logger: ^1.4.0
  # https://pub.flutter-io.cn/packages/json_annotation
  json_annotation: ^4.9.0
  # https://pub-web.flutter-io.cn/packages/flutter_screenutil
  flutter_screenutil: ^5.9.3
  # https://pub-web.flutter-io.cn/packages/infinite_scroll_pagination
  infinite_scroll_pagination: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  analyzer: any
  dart_code_metrics: any
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.1.11
  flutter_gen_runner: ^5.3.1
  # https://pub.flutter-io.cn/packages/json_serializable
  json_serializable: ^6.8.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/launcher_icon.png"

flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  assets:
    enabled: true
  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    # lottie: true

  # colors:
  #   inputs:
  #     - assets/color/colors.xml
  
flutter:
  # generate: true
  uses-material-design: true
  assets:
    - assets/locales/
    - assets/images/
    - assets/images/tab-icons/
    
  fonts:
      - family: Arial
        fonts:
          - asset: assets/fonts/Arial.ttf
      - family: Arial-Bold
        fonts:
          - asset: assets/fonts/Arial-Bold.ttf
